### ISSUE TITLE
Create flatpak manifest using the upcoming Odin SDK

### ISSUE THREAD

**Issue by hanaral** [avojak/iridium#127]
The new AppCenter will require a manifest that uses the `io.elementary.Sdk`, so I went ahead and made one that seems to work flawlessly with only one update needed.
The only change that the meson build system needs is to specify `gtksourceview-4` because 3 uses make rather than meson (which is a headache). Luckily 4 seems to not have any negative impact compared to 3, and is also newer.

The flatpak manifest:
```
app-id: com.github.avojak.iridium
runtime: io.elementary.Sdk
runtime-version: '0.1.0'
sdk: io.elementary.Sdk
command: com.github.avojak.iridium
finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --share=network
  - --device=dri
  # needed for perfers-color-scheme
  - --system-talk-name=org.freedesktop.Accounts

cleanup:
- '/include'
- '/lib/pkgconfig'
- '/lib/cmake'
- '/lib/girepository-1.0'
- '/share/gir-1.0'
- '/share/vala'
- '*.a'
- '*.la'

modules:
  - name: gtksourceview
    buildsystem: meson
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/gtksourceview.git
        tag: '4.8.0'
  - name: granite

    buildsystem: meson
    cleanup:
      - /bin
      - /share/applications
    sources:
      - type: git
        url: https://github.com/elementary/granite.git
        commit: 1e36f82d0b32d7d7cc7eb3ceda7b46ba143f775c

  - name: iridium
    buildsystem: meson
    sources:
      - type: dir
        path: .
```

Changes needed to the dependency section of src/meson.build:
```
        dependency('gtksourceview-4')
```

If you want to test it you will have to either:
- Build the SDK from the [flatpak-platform repo](https://github.com/elementary/flatpak-platform) (make sure to remove any mention of org.gnome.Sdk.Debug from the json file ninja produces unless you want it to take half a day and over 10Gb)
- Download the precompiled io.elementary.Sdk.flatpak bundle I [uploaded](https://www.dropbox.com/s/3mg7uxa5nbtc79a/io.elementary.Sdk.flatpak?dl=0) to Dropbox
